# numpy and matplotlib

In [1]:
import numpy as np
import matplotlib as mlt
import pandas as pd
import pandas_datareader

Lets start with numpy and then use other library

In [2]:
list = (1,2,3,4,5,7,6)


Here we are converting a list into an array by using the numpy. The type is an ndim-array

We can directly assing it to an array 

In [3]:
np.array(list)

array([1, 2, 3, 4, 5, 7, 6])

In [4]:
type(np.array(list))

numpy.ndarray

In [5]:
arr =  np.array([0,1,2,3,4,5,6,7,8,9])

In [6]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Arange or np.arange is used to create an array with start value ,end value , step size and dtype

below is the example for the same 

In [7]:
a = np.arange(5,15)
b = np.arange(5,15,2,dtype=float)
print (a)
print(b)

[ 5  6  7  8  9 10 11 12 13 14]
[  5.   7.   9.  11.  13.]


In Numpy we have quickways to create zeroes , diagonal 1 , ones other kind of in bulit function 


np.zeros has values ( shape , dtype= , order=) all values are 0


np.ones has values ( shape , dtype= , order=) all values are  1

In [8]:
a = np.zeros(5)
b= np.zeros([5,6])
c= np.zeros([5,6],dtype=np.int64)
print(a)
print("The default is float \n" , b)
print("Changed the dtype to int \n",c)

[ 0.  0.  0.  0.  0.]
The default is float 
 [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
Changed the dtype to int 
 [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [9]:
a = np.ones(2)
b = np.ones((3,5))
c = np.ones((2,4),dtype=np.int16)
print(a)
print("The default is float \n" , b)
print("Changed the dtype to int \n",c)

[ 1.  1.]
The default is float 
 [[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
Changed the dtype to int 
 [[1 1 1 1]
 [1 1 1 1]]


We have another function known as eye which takes one parameter for diagonal element

In [61]:
a = np.eye(2)
b = np.eye((5))
c = np.eye((2),dtype=np.int32)
print(a)
print("The default is float \n" , b)
print("Changed the dtype to int \n",c)
c.nonzero()

[[ 1.  0.]
 [ 0.  1.]]
The default is float 
 [[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
Changed the dtype to int 
 [[1 0]
 [0 1]]


(array([0, 1], dtype=int64), array([0, 1], dtype=int64))

Another function is np.linspace: Gives Lineraly/Evenly spaced values 


np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [11]:
np.linspace(2.0, 3.0, num=100)

array([ 2.        ,  2.01010101,  2.02020202,  2.03030303,  2.04040404,
        2.05050505,  2.06060606,  2.07070707,  2.08080808,  2.09090909,
        2.1010101 ,  2.11111111,  2.12121212,  2.13131313,  2.14141414,
        2.15151515,  2.16161616,  2.17171717,  2.18181818,  2.19191919,
        2.2020202 ,  2.21212121,  2.22222222,  2.23232323,  2.24242424,
        2.25252525,  2.26262626,  2.27272727,  2.28282828,  2.29292929,
        2.3030303 ,  2.31313131,  2.32323232,  2.33333333,  2.34343434,
        2.35353535,  2.36363636,  2.37373737,  2.38383838,  2.39393939,
        2.4040404 ,  2.41414141,  2.42424242,  2.43434343,  2.44444444,
        2.45454545,  2.46464646,  2.47474747,  2.48484848,  2.49494949,
        2.50505051,  2.51515152,  2.52525253,  2.53535354,  2.54545455,
        2.55555556,  2.56565657,  2.57575758,  2.58585859,  2.5959596 ,
        2.60606061,  2.61616162,  2.62626263,  2.63636364,  2.64646465,
        2.65656566,  2.66666667,  2.67676768,  2.68686869,  2.69

In [12]:
np.linspace(2.0, 3.0, num=5, endpoint=False) # doesnt involve the 3

array([ 2. ,  2.2,  2.4,  2.6,  2.8])

In [13]:
np.linspace(2.0, 3.0, num=50, retstep=True) # retstep returns the stepsize of the sampling if false doesnt return

(array([ 2.        ,  2.02040816,  2.04081633,  2.06122449,  2.08163265,
         2.10204082,  2.12244898,  2.14285714,  2.16326531,  2.18367347,
         2.20408163,  2.2244898 ,  2.24489796,  2.26530612,  2.28571429,
         2.30612245,  2.32653061,  2.34693878,  2.36734694,  2.3877551 ,
         2.40816327,  2.42857143,  2.44897959,  2.46938776,  2.48979592,
         2.51020408,  2.53061224,  2.55102041,  2.57142857,  2.59183673,
         2.6122449 ,  2.63265306,  2.65306122,  2.67346939,  2.69387755,
         2.71428571,  2.73469388,  2.75510204,  2.7755102 ,  2.79591837,
         2.81632653,  2.83673469,  2.85714286,  2.87755102,  2.89795918,
         2.91836735,  2.93877551,  2.95918367,  2.97959184,  3.        ]),
 0.020408163265306121)

In [14]:
a = [1,5,4,2]
var = int (input("Enter a number"))
print(a[var%len(a)])

Enter a number4
1


In [15]:
a = [1,2,6,7]
if(len(a)>0):
    counter = len(a)//2
    #print (counter)
    if(counter == 2):
        for x in range(len(a)):
            res1 = a[x%len(a)] + a[(x+1)%len(a)]
            res2 = a[(x+2)%len(a)] + a[(x+3)%len(a)]
            if (res1==res2):
                 print(a[x%len(a)] , a[(x+1)%len(a)]) 

2 6
7 1


Most times during using the Neural Network we need to initlize the array randomly and make use of random function 

In [20]:
np.random.random(2)

array([ 0.56652764,  0.35158779])

In [17]:
np.random.randint(6 , size=3)

array([5, 3, 1])

In [56]:
array = np.random.randint(4 ,size=(2,2))
print(array)

[[3 2]
 [2 1]]


In [57]:
array.ravel()   #flatens the array or matrix 

array([3, 2, 2, 1])

In [59]:
array.nonzero()

(array([0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1], dtype=int64))

In [27]:
a,b = 0,0.1 
np.random.normal(a,b,(8)) # This is about std deviation and all press shift+tab and read again

array([-0.03927103,  0.22592904, -0.0060875 ,  0.02117457,  0.21165341,
        0.04482198,  0.19256405,  0.15449264])

### Some array operations of numpy

In [35]:
np.random.seed(101)

arr = np.random.randint(0,100,10)

In [36]:
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [38]:
arr.max()

95

In [39]:
arr.min()

9

In [40]:
arr.argmin()  #index of the lowest value is given 

7

In [41]:
arr.argmax() # max value index 

0

In [42]:
ary = arr.copy()

In [43]:
ary

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [44]:
ary.ravel()

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [55]:
ary.nonzero()

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [62]:
arr.mean()

60.799999999999997

In [64]:
arr.reshape(5,2)

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

In [72]:
new_ary = ary.reshape(2,5)
print(new_ary)

[[95 11 81 70 63]
 [87 75  9 77 40]]


In [74]:
new_ary.shape[0]  # shape[0] brings out the number of rows and shape[1] -- column number is returned 

2

In [75]:
new_ary.shape[1]

5

Arithmatic operations and checking the dot product and matmul operation

In [83]:
###### Arthimetic
A =  np.random.randint(-5,10 ,size=(3,2))
B = np.random.randint(-5,10 ,size=(3,2))
print(A)
print (B)

[[-2 -3]
 [-2  9]
 [ 5 -2]]
[[ 7  2]
 [-1  6]
 [ 3  1]]


In [85]:
#### ADDITION
result = A+B
print (result)
np.add(A,B)

[[ 5 -1]
 [-3 15]
 [ 8 -1]]


array([[ 5, -1],
       [-3, 15],
       [ 8, -1]])

In [86]:
#### Sub 
result = A-B
print (result)
np.subtract(A,B)

[[-9 -5]
 [-1  3]
 [ 2 -3]]


array([[-9, -5],
       [-1,  3],
       [ 2, -3]])

In [91]:
#### Multiplication
result = A*B
print (result)
res0 = np.multiply(A,B)
res1 = np.matmul(A, np.transpose(B))
res2 = np.dot(A,np.transpose(B))
print(res1)
print(res2)
print(res0)

[[-14  -6]
 [  2  54]
 [ 15  -2]]
[[-20 -16  -9]
 [  4  56   3]
 [ 31 -17  13]]
[[-20 -16  -9]
 [  4  56   3]
 [ 31 -17  13]]
[[-14  -6]
 [  2  54]
 [ 15  -2]]


In [97]:
#### div 
result = A/B
print (result)
np.divide(A,B)



#### div2
result = A//B
print (result)
np.divmod(A,B)

[[-0.28571429 -1.5       ]
 [ 2.          1.5       ]
 [ 1.66666667 -2.        ]]
[[-1 -2]
 [ 2  1]
 [ 1 -2]]


(array([[-1, -2],
        [ 2,  1],
        [ 1, -2]], dtype=int32), array([[5, 1],
        [0, 3],
        [2, 0]], dtype=int32))

In [109]:
#### other functions like sin cos log exp and sqrt also can be performed on these matrix

print ("SINE\n",np.sin(A))
print ("COS\n",np.cos(A))


print ("EXP\n",np.exp(A))

print ("LOG\n",np.log10(A))

print ("SQUARE\n",np.square(A))

print ("SQRT\n",np.sqrt(A))

print ("Ele wise comparision --- \n", np.array_equal(A,B))

#### nan is not a number as - squrt is not a number and -log also

SINE
 [[-0.90929743 -0.14112001]
 [-0.90929743  0.41211849]
 [-0.95892427 -0.90929743]]
COS
 [[-0.41614684 -0.9899925 ]
 [-0.41614684 -0.91113026]
 [ 0.28366219 -0.41614684]]
EXP
 [[  1.35335283e-01   4.97870684e-02]
 [  1.35335283e-01   8.10308393e+03]
 [  1.48413159e+02   1.35335283e-01]]
LOG
 [[        nan         nan]
 [        nan  0.95424251]
 [ 0.69897            nan]]
SQUARE
 [[ 4  9]
 [ 4 81]
 [25  4]]
SQRT
 [[        nan         nan]
 [        nan  3.        ]
 [ 2.23606798         nan]]
Ele wise comparision --- 
 False


C:\Users\dumapath\AppData\Local\conda\conda\envs\my_root\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in log10
  if __name__ == '__main__':
C:\Users\dumapath\AppData\Local\conda\conda\envs\my_root\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in sqrt
  del sys.path[0]


In [82]:
mat = np.arange(0,100).reshape(10,10)
print (mat)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


We can perform indexing and slicing operations

In [111]:
mat[0,0]

0

In [113]:
mat[9,5]

95

In [114]:
mat.shape[0]

10

In [134]:
#####ALL the rows in first column
val = mat[0:10,0]
print (val)
val.shape

[ 0 10 20 30 40 50 60 70 80 90]


(10,)

In [125]:
mat[2:8,3:4]   # doesnt include the end values

array([[23],
       [33],
       [43],
       [53],
       [63],
       [73]])

In [126]:
mat[2:,3:] 

array([[23, 24, 25, 26, 27, 28, 29],
       [33, 34, 35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47, 48, 49],
       [53, 54, 55, 56, 57, 58, 59],
       [63, 64, 65, 66, 67, 68, 69],
       [73, 74, 75, 76, 77, 78, 79],
       [83, 84, 85, 86, 87, 88, 89],
       [93, 94, 95, 96, 97, 98, 99]])

In [127]:
mat[:2,:3] 

array([[ 0,  1,  2],
       [10, 11, 12]])

In [139]:
aray = np.array([1,2,3,4,5,6])
print (aray.shape)

(6,)


(6,)

In [142]:
#masking

mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])