# TENSORFLOW YT

In [2]:
import tensorflow as tf

In [3]:
a = tf.constant(5)
b= tf.constant(3)

In [4]:
with tf.Session() as sess:
    c = a+b;
    res = sess.run(c)
    print (res)

8


We can see above the use of Session inside a with block 


### MULTI DIMENSIONAL ARRAY 

In [5]:
scalar = tf.constant([2])
vector = tf.constant([1,2,3])
matrix = tf.constant([[1,2,3],[4,5,6]])
tensor = tf.constant([ [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]] ])

In [6]:
with tf.Session() as ses:
    resu = ses.run(scalar)
    print ("Scalar", resu)
    resu = ses.run(vector)
    print ("Vector",resu)
    resu = ses.run(matrix)
    print ("Matrix",resu)
    resu = ses.run(tensor)
    print ("Tesnor",resu)

Scalar [2]
Vector [1 2 3]
Matrix [[1 2 3]
 [4 5 6]]
Tesnor [[[1 2 3]
  [4 5 6]
  [1 2 3]]

 [[1 2 3]
  [4 5 6]
  [1 2 3]]

 [[1 2 3]
  [4 5 6]
  [1 2 3]]]


In [19]:
tensor1 = tf.constant([ [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]] ])
tensor2 = tf.constant([ [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]] ])

tensor3 = tensor1+tensor2
tensor4 = tf.add(tensor1,tensor2)

with tf.Session() as ses:
    resu = ses.run(tensor3)
    print ("tensor3 \n", resu ,"\n")
    resu = ses.run(tensor4)
    print ("tensor4 \n", resu)


tensor3 
 [[[ 2  4  6]
  [ 8 10 12]
  [ 2  4  6]]

 [[ 2  4  6]
  [ 8 10 12]
  [ 2  4  6]]

 [[ 2  4  6]
  [ 8 10 12]
  [ 2  4  6]]] 

tensor4 
 [[[ 2  4  6]
  [ 8 10 12]
  [ 2  4  6]]

 [[ 2  4  6]
  [ 8 10 12]
  [ 2  4  6]]

 [[ 2  4  6]
  [ 8 10 12]
  [ 2  4  6]]]


## General multiplication vs Matmul (dot product)

## General multiplication 

In [7]:
tensor1 = tf.constant([ [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]] ])
tensor2 = tf.constant([ [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]] ])

tensor3 = tensor1 * tensor2
tensor4 = tf.multiply (tensor1,tensor2)

with tf.Session() as ses:
    resu = ses.run(tensor3)
    print ("tensor3 \n", resu ,"\n")
    resu = ses.run(tensor4)
    print ("tensor4 \n", resu)


tensor3 
 [[[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]

 [[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]

 [[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]] 

tensor4 
 [[[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]

 [[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]

 [[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]]


## General vs Matmul 

In [12]:
tensor1 = tf.constant([ [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]] ])
tensor2 = tf.constant([ [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]] ])

tensor3 = tensor1*tensor2
tensor4 = tf.matmul(tensor1,tensor2)

with tf.Session() as ses:
    resu = ses.run(tensor3)
    print ("tensor3 \n", resu ,"\n")
    resu = ses.run(tensor4)
    print ("tensor4 \n", resu)
    resu = ses.run(tf.zeros([2,3]))
    print ("eye \n", resu)

tensor3 
 [[[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]

 [[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]

 [[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]] 

tensor4 
 [[[12 18 24]
  [30 45 60]
  [12 18 24]]

 [[12 18 24]
  [30 45 60]
  [12 18 24]]

 [[12 18 24]
  [30 45 60]
  [12 18 24]]]
eye 
 [[ 0.  0.  0.]
 [ 0.  0.  0.]]


## TF Zeros vs Eye vs Ones

In [21]:
ZERO = tf.zeros([2,3] , dtype=tf.int64)
ZERO1 = tf.zeros(2)
EYE = tf.eye(5)
ONES = tf.ones(2)
ONES1 = tf.ones([2,6])


with tf.Session() as sess:
    resu = sess.run(ZERO)
    print ("Zeroes \n", resu ,"\n")
    resu = sess.run(ZERO1)
    print ("ZERO1 \n", resu)
    resu = sess.run(EYE)
    print ("Eye \n", resu)
    resu = sess.run(ONES)
    print ("Ones \n", resu)
    resu = sess.run(ONES1)
    print ("Ones1 \n", resu) 

Zeroes 
 [[0 0 0]
 [0 0 0]] 

ZERO1 
 [ 0.  0.]
Eye 
 [[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
Ones 
 [ 1.  1.]
Ones1 
 [[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]


In [26]:
a = [1,5,4,2]
var = int (input("Enter a number"))
print(a[var%len(a)])

Enter a number3
2


In [32]:
a = [1,2,6,7]
if(len(a)>0):
    counter = len(a)//2
    #print (counter)
    if(counter == 2):
        for x in range(len(a)):
            res1 = a[x%len(a)] + a[(x+1)%len(a)]
            res2 = a[(x+2)%len(a)] + a[(x+3)%len(a)]
            if (res1==res2):
                 print(a[x%len(a)] , a[(x+1)%len(a)]) 

2 6
7 1
