# TENSORFLOW YT

In [1]:
import tensorflow as tf

In [2]:
a = tf.constant(5)
b= tf.constant(3)

In [3]:
with tf.Session() as sess:
    c = a+b;
    res = sess.run(c)
    print (res)

8


We can see above the use of Session inside a with block 


### MULTI DIMENSIONAL ARRAY 

In [10]:
scalar = tf.constant([2])
vector = tf.constant([1,2,3])
matrix = tf.constant([[1,2,3],[4,5,6]])
tensor = tf.constant([ [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]] ])

In [14]:
with tf.Session() as ses:
    resu = ses.run(scalar)
    print ("Scalar", resu)
    resu = ses.run(vector)
    print ("Vector",resu)
    resu = ses.run(matrix)
    print ("Matrix",resu)
    resu = ses.run(tensor)
    print ("Tesnor",resu)

Scalar [2]
Vector [1 2 3]
Matrix [[1 2 3]
 [4 5 6]]
Tesnor [[[1 2 3]
  [4 5 6]
  [1 2 3]]

 [[1 2 3]
  [4 5 6]
  [1 2 3]]

 [[1 2 3]
  [4 5 6]
  [1 2 3]]]


In [19]:
tensor1 = tf.constant([ [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]] ])
tensor2 = tf.constant([ [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]] ])

tensor3 = tensor1+tensor2
tensor4 = tf.add(tensor1,tensor2)

with tf.Session() as ses:
    resu = ses.run(tensor3)
    print ("tensor3 \n", resu ,"\n")
    resu = ses.run(tensor4)
    print ("tensor4 \n", resu)


tensor3 
 [[[ 2  4  6]
  [ 8 10 12]
  [ 2  4  6]]

 [[ 2  4  6]
  [ 8 10 12]
  [ 2  4  6]]

 [[ 2  4  6]
  [ 8 10 12]
  [ 2  4  6]]] 

tensor4 
 [[[ 2  4  6]
  [ 8 10 12]
  [ 2  4  6]]

 [[ 2  4  6]
  [ 8 10 12]
  [ 2  4  6]]

 [[ 2  4  6]
  [ 8 10 12]
  [ 2  4  6]]]


## General multiplication vs Matmul (dot product)

## General multiplication 

In [21]:
tensor1 = tf.constant([ [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]] ])
tensor2 = tf.constant([ [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]] ])

tensor3 = tensor1 * tensor2
tensor4 = tf.multiply (tensor1,tensor2)

with tf.Session() as ses:
    resu = ses.run(tensor3)
    print ("tensor3 \n", resu ,"\n")
    resu = ses.run(tensor4)
    print ("tensor4 \n", resu)


tensor3 
 [[[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]

 [[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]

 [[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]] 

tensor4 
 [[[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]

 [[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]

 [[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]]


## General vs Matmul 

In [25]:
tensor1 = tf.constant([ [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]] ])
tensor2 = tf.constant([ [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]], [[1,2,3],[4,5,6],[1,2,3]] ])

tensor3 = tensor1*tensor2
tensor4 = tf.matmul(tensor1,tensor2)

with tf.Session() as ses:
    resu = ses.run(tensor3)
    print ("tensor3 \n", resu ,"\n")
    resu = ses.run(tensor4)
    print ("tensor4 \n", resu)
    resu = ses.run(tf.eye(2))
    print ("eye \n", resu)

tensor3 
 [[[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]

 [[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]

 [[ 1  4  9]
  [16 25 36]
  [ 1  4  9]]] 

tensor4 
 [[[12 18 24]
  [30 45 60]
  [12 18 24]]

 [[12 18 24]
  [30 45 60]
  [12 18 24]]

 [[12 18 24]
  [30 45 60]
  [12 18 24]]]
eye 
 [[ 1.  0.]
 [ 0.  1.]]
